name: vsn
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow-gpu
  - python=3.7
  - pip
  - pip:
    - cloudpickle
    - dill
    - gym
    - numpy
    - opencv-python
    - pickle5
    - pyyaml
    - tensorflow-probability==0.12.0
    - yacs
    - scikit-image
    - pandas
    - matplotlib