name: vsn
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow-gpu
  - python=3.7
  - pip
  - pip:
    - cloudpickle
    - dill
    - gym
    - numpy
    - opencv-python
    - pickle5
    - pyyaml
    - tensorflow-probability
    - yacs
    - scikit-image
    - miniworld